### ISSUE TITLE
Looks like they have done an update - solution in comments.

### ISSUE THREAD

**Issue by taux1c** [Amenly/onlyfans-scraper#194]
Seem to have a new issue with downloading. 

`- 336 posts
 -- 334 photos
 -- 48 videos
 -- 4 audios
- 46 archived posts
 + Getting pinned media...
 + Getting timeline media...
 + Getting archived media...
Traceback (most recent call last):
  File "/usr/local/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 328, in main
    process_prompts()
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 214, in process_prompts
    do_download_content(headers, username, model_id)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 138, in do_download_content
    combined_urls = process_areas(headers, username, model_id)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 102, in process_areas
    combined_urls = process_areas_all(headers, username, model_id)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 89, in process_areas_all
    highlights_urls = process_highlights(headers, model_id)
  File "/usr/local/lib/python3.8/dist-packages/revolution/revolution.py", line 45, in wrapper
    result = func(*margs, **mkwargs)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/scraper.py", line 38, in process_highlights
    highlights_ids = highlights.parse_highlights(highlights_)
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/api/highlights.py", line 42, in parse_highlights
    highlight_ids = [highlight['id'] for highlight in highlights]
  File "/usr/local/lib/python3.8/dist-packages/onlyfans_scraper/api/highlights.py", line 42, in <listcomp>
    highlight_ids = [highlight['id'] for highlight in highlights]
TypeError: string indices must be integers
 | Getting highlights...                  `

**Comment by Acman2322** [comment]
Yes I believe it is down , who will fix ?

**Comment by taux1c** [comment]
After digging through the code I don't think the error is completely telling us the whole story. It seems that onlyfans may have added a requirement to access highlights because every time I hit that url my cookie is dead. Have to re-sign-in.

**Comment by cuenta111** [comment]
yeah scraper not working, facing issue

**Comment by cuenta111** [comment]
Traceback (most recent call last):
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 214, in process_prompts
    do_download_content(headers, username, model_id)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 138, in do_download_content
    combined_urls = process_areas(headers, username, model_id)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 102, in process_areas
    combined_urls = process_areas_all(headers, username, model_id)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 89, in process_areas_all
    highlights_urls = process_highlights(headers, model_id)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\revolution\revolution.py", line 45, in wrapper
    result = func(*margs, **mkwargs)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 38, in process_highlights
    highlights_ids = highlights.parse_highlights(highlights_)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\api\highlights.py", line 42, in parse_highlights
    highlight_ids = [highlight['id'] for highlight in highlights]
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\api\highlights.py", line 42, in <listcomp>
    highlight_ids = [highlight['id'] for highlight in highlights]
TypeError: string indices must be integers

C:\Users\dskter>


Traceback (most recent call last):
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 214, in process_prompts
    do_download_content(headers, username, model_id)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 138, in do_download_content
    combined_urls = process_areas(headers, username, model_id)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 102, in process_areas
    combined_urls = process_areas_all(headers, username, model_id)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 89, in process_areas_all
    highlights_urls = process_highlights(headers, model_id)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\revolution\revolution.py", line 45, in wrapper
    result = func(*margs, **mkwargs)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 38, in process_highlights
    highlights_ids = highlights.parse_highlights(highlights_)
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\api\highlights.py", line 42, in parse_highlights
    highlight_ids = [highlight['id'] for highlight in highlights]
  File "C:\Users\dskter\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\api\highlights.py", line 42, in <listcomp>
    highlight_ids = [highlight['id'] for highlight in highlights]
TypeError: string indices must be integers

**Comment by cuenta111** [comment]
getting this error

**Comment by taux1c** [comment]
From what I found here (https://github.com/DIGITALCRIMINALS/OnlyFans/issues/516#issuecomment-1192851719) it looks like they changed the way they are passing media.

**Comment by taux1c** [comment]
Fixed it, have it working on my fork. https://github.com/taux1c/onlyfans-scraper also made a pull request here but looks like it may not be accepted.

**Comment by Amenly** [comment]
I've been away for a long time but I'll try and come back around to fix things up. It seems like they changed how highlights are managed so, in the meantime, you'll have to ignore highlights. Posts, archived posts, and messages should be scraped exactly as they have been.

@taux1c also maybe I'm blind but I don't see your pull request here. I'll accept it if you submit one :)

**Comment by taux1c** [comment]
aaaaeee There's my favorite dev! lol I have very little knowledge of how github works so I will check it again. It's a super simple fix.

**Comment by taux1c** [comment]
So I made the first pull request to my fork 🤣  I was like wait ... how do I have one. Then I realized what I did but I submitted one to you now.

**Comment by havingfun2500** [comment]
How may I update the script to the latest version with fix? I ran the pip command but it still have the highlights problem.

**Comment by Maj-ew** [comment]
I downloaded https://github.com/taux1c/onlyfans-scraper code/zip and then copy pasted everything, pressed change files (40) but it doesn't work still. Can someone help, still same error I think
